### ISSUE TITLE
Breaking Up Large TeX Files

### ISSUE THREAD

**Issue by matthewsot** [UC-Davis-CS-Tutoring/Study-Guides#6]
I personally prefer, ex. for the ECS 20 study guide, to have each section be its own .tex file, then \input them all in the main tex file. If there are no major objections, I'll make that change to the ECS 20 study guide and any future ones.

**Comment by aakash1104** [comment]
I agree! When I firs started writing this, I didn't expect the file to be big enough to break it apart in to separate `.tex` files. Moving forward, we should do this!

**Comment by matthewsot** [comment]
Closed as of PR #7
